### ISSUE TITLE
Código replicado na mensurationDAO e costDAO

### ISSUE THREAD

**Issue by wagnerjs** [gldpi2/gldpi2#1]
Código replicado, refatorar.

**Comment by matheusfreire** [comment]
Wagner, no repositório não tem a classe mensurationDAO. Verifique se você criou e não a subiu para o repositório.

**Comment by wagnerjs** [comment]
Verdade.. Não fiz a DAO da mensuration na correria de quarta.. Mas o que ta no GraphTestDao é parte da DAO da mensuration.

**Comment by matheusfreire** [comment]
Tranquilo, irei refatorar o código, baseado naquele código

**Comment by matheusfreire** [comment]
Código refatorado, implementei tendo como base a do graphtestDAO (até a nomenclatura dos métodos) e acho que conseguir deixar o código robusto e coeso. Da uma olhada lá.

**Comment by wagnerjs** [comment]
Não achei a mensurationDao no repositorio.

**Comment by matheusfreire** [comment]
Era para fazer, tipo pegando a mesma coisa do graphtest?

**Comment by wagnerjs** [comment]
Sim.. Mas nao tá no repo.. Tanto que o projeto tá quebrado falando que não tem a classe. Não deve ter sido acidionado no commit.

**Comment by matheusfreire** [comment]
Eu criei só o nome, a lógica do mensuration eu achei que tu iria colocar, mas eu faço aqui rapidinho. E subo para o repo.

**Comment by wagnerjs** [comment]
Tá.. Cuidado pra não esquecer da camada controller.. dao > ctrl > view

Abraço
