### ISSUE TITLE
Problema ao iniciar tela principal.

### ISSUE THREAD

**Issue by wagnerjs** [gldpi2/gldpi2#2]
![screenshot from 2013-06-27 20 29 03](https://f.cloud.github.com/assets/2731235/719386/80e76416-df81-11e2-8493-6d4a19db5b91.png)

O icone está na pasta correta mas não funciona.
Print em anexo.

O mesmo problema acontece com todos os que tentam usar o caminho de icones.

**Comment by kallahir** [comment]
Então Wagner, acabei de dar pull no projeto e rodar ele, não acontece isso aqui.

Funciona perfeitamente.

**Comment by wagnerjs** [comment]
Eu também acabei de dar pull.

**Comment by kallahir** [comment]
Putz então não tenho ideia. Inclusive isso tudo foi feito no computador do Greg, então não é nada local meu. Faz o seguinte só pra você conseguir rodar apaga o menu ai de relatórios, ele inclusive estava sendo escondido porque não vamos usar agora. Depois eu coloco denovo. Abs.

**Comment by wagnerjs** [comment]
Tentei fazer isso, não deu certo.
O problema não é o menu de relatório, mas algum problema com o caminho dos ícones que estão no caminho certo.

**Comment by kallahir** [comment]
Tá então não sei cara. Tenta só tirar o icone do menu.

**Comment by wagnerjs** [comment]
Eu não vou mexer com isso agora.
Só coloquei pra saber que, pelo menos comigo, está dando problema.

**Comment by kallahir** [comment]
Tranquilo!

**Comment by fernandosouzs** [comment]
caminho de ícone não dá erro assim não.
O ícone apenas não é exibido!

2013/6/27 kallahir notifications@github.com

> Tranquilo!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/gldpi2/gldpi2/issues/2#issuecomment-20162799
> .

## 

Fernando de Souza Santos
Graduando em Engenharia de Software pela Universidade de Brasília - UnB
http://br.linkedin.com/in/fernandosouzs

"Senhor, confio em Ti."

**Comment by arturpc** [comment]
Eu tava com um problema parecido até dar o commit com o ícone que eu tava
exibindo.... até localmente ele dava null pointer exception.... vê se
comitando o ícone no /icons não resolve o problema!

Em 27 de junho de 2013 21:47, Fernando notifications@github.com escreveu:

> caminho de ícone não dá erro assim não.
> O ícone apenas não é exibido!
> 
> 2013/6/27 kallahir notifications@github.com
> 
> > Tranquilo!
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/gldpi2/gldpi2/issues/2#issuecomment-20162799>
> > .
> 
> ## 
> 
> Fernando de Souza Santos
> Graduando em Engenharia de Software pela Universidade de Brasília - UnB
> http://br.linkedin.com/in/fernandosouzs
> 
> "Senhor, confio em Ti."
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/gldpi2/gldpi2/issues/2#issuecomment-20164491
> .

## 

Artur Potiguara Carvalho
Graduando em Engenharia de Software
(Universidade de Brasília - Campus Gama)

**Comment by wagnerjs** [comment]
Como assim? Dar commit nos itens que estão no repositório?

**Comment by arturpc** [comment]
commit no ícone! eu adicionei um ícone no /icons e ele não rodava.... qdo
eu commitei essa adição na pasta /icons, deu certo. Sacou?

Em 28 de junho de 2013 09:30, wagnerjs notifications@github.com escreveu:

> Como assim? Dar commit nos itens que estão no repositório?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/gldpi2/gldpi2/issues/2#issuecomment-20185290
> .

## 

Artur Potiguara Carvalho
Graduando em Engenharia de Software
(Universidade de Brasília - Campus Gama)

**Comment by gregincs** [comment]
velho, aqui nem tá rodando mais... pode ser por causa da internet pra conectar o banco de dados... foda que só vou poder quando sair do estágio pq o tcu n tem certificado na conexao com o ubuntu...

**Comment by matheusfreire** [comment]
Ontem conseguir rodar tranquilo o sistema. Não deu nenhum problema em relação a este ícone. E eu dei pull antes de usar. Só ta dando problema com o wagner ou mais alguém? Pode ser questão do SO também. Greg, depois da uma verificada se roda no seu, já que você e o wagner estão rodando no mesmo SO.
Abraços.

**Comment by gregincs** [comment]
então dijas... eu testei aqui, mas deu erro no mysql connector, acho que era por causa da internet... se quiserem, assim que eu chegar em casa, umas 17h eu testo, pq aqui no tcu n tem os certificados pra conectar no ubuntu e n sei como resolver isso

**Comment by kallahir** [comment]
Galera tirando a janela do Artur que não funciona de jeito nenhum o resto ta OK!

**Comment by arturpc** [comment]
Como assim?

Em 28 de junho de 2013 12:44, kallahir notifications@github.com escreveu:

> Galera tirando a janela do Artur que não funciona de jeito nenhum o resto
> ta OK!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/gldpi2/gldpi2/issues/2#issuecomment-20196190
> .

## 

Artur Potiguara Carvalho
Graduando em Engenharia de Software
(Universidade de Brasília - Campus Gama)

**Comment by kallahir** [comment]
Dei outro pull agora mesmo e tá funcionando. Falta só integrar com a tela principal. Acho que a tabela pode ficar maior, e adiciona um campo se o perfil está ativo ou desativado.Aqueles icones você pode trocar por interrogações. Ficou legal. Vamos tentar fazer já tudo na janela principal. Abs.

**Comment by wagnerjs** [comment]
Só eu estou tendo esse problema ou mais alguém?

Abraços.
