### ISSUE TITLE
Problema ao iniciar gráfico de curva de carga na tela principal

### ISSUE THREAD

**Issue by wagnerjs** [gldpi2/gldpi2#3]

**Comment by gregincs** [comment]
foi mudado algum metodo, adiconado variaveis no metodo de inicialização ou algo do tipo na classe do Chart da curva de carga?? se sim a gente resolve isso rapidinho assim que eu tiver internet pra dar pull ;)

**Comment by wagnerjs** [comment]
Resolvido. Só documentando os erros encontrados.
