### ISSUE TITLE
Fechar UpdaterLoadCurveThread ao mudar de tela.

### ISSUE THREAD

**Issue by wagnerjs** [gldpi2/gldpi2#4]

**Comment by gregincs** [comment]
wagner... n entendi direito essa issue. Devo mandar um thread.stop(); quando mudar de tela?

**Comment by wagnerjs** [comment]
Isso! Pq se nao ela fica em aberto.. Abraço

**Comment by gregincs** [comment]
entendi... o problema é que a thread tem que rodar no main menu tbm não é? fiz um teste mandando o thread.stop(); em um dos botoes de voltar e ele dava problema de acesso ao bd.
