### ISSUE TITLE
Problema ao carregar gráfico de custo na tela principal.

### ISSUE THREAD

**Issue by wagnerjs** [gldpi2/gldpi2#5]
Recomendo ver como fiz a de curva de carga, que já ta usando o MVC com DAO certinho e tá bem simples a chamadas na view.

**Comment by matheusfreire** [comment]
Irei olhar.

**Comment by gregincs** [comment]
provavelmente mesmo problema com o de carga, mudança de metodos e parâmetros na chart

**Comment by matheusfreire** [comment]
Tentei um método aqui, mas não deu certo. Agora não posso mexer mais, surgiu uma demanda no estágio. Assim que eu tiver tempo tento fazer as 2 coisas rodar. Porém o gráfico na tela inicial está rodando corretamente, falta só as informações em tempo real na tela de custo.

**Comment by gregincs** [comment]
blz dijas, la em p.i. 2 a gente ve isso... além disso o itallo pediu pra eu prototipar outra interface, aí iremos querer a opinião de vcs. bgs e abs

**Comment by matheusfreire** [comment]
Arrumado! Pode fechar, Wagner?

**Comment by wagnerjs** [comment]
Eu vi que não ta dando null pointer mas quando rodo ele não atualiza real-time.

**Comment by matheusfreire** [comment]
No meu pc não atualiza nem o meu nem o teu. Não sei por que.

**Comment by wagnerjs** [comment]
aqui no meu atualiza.. tem que rodar a rotina que simula.. vou deixar ela rodando aqui pra vc atualizar ai e ver agora!

**Comment by matheusfreire** [comment]
Atualiza, de boa. Pode parar a rotina ai, vou arrumar aqui agora. Vlw

**Comment by wagnerjs** [comment]
Não entendi.
Ok.
